Repository TooNovel/TooNovel-BE, pull requests merged in 2023-06, with the labels that each got.

#87 [REFACTOR] 소설 상세 조회 기능 수정
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/PlatformResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java
Labels: :sparkles: Feature, :recycle: refactor

#92 [FEAT] 메신저 기능 구현
  build.gradle
  src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java
  src/main/java/com/yju/toonovel/domain/chatting/controller/ChatWebSocketController.java
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatRoomAllRequestDto.java
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatRoomResponseDto.java
  src/main/java/com/yju/toonovel/domain/chatting/entity/Chat.java
  src/main/java/com/yju/toonovel/domain/chatting/entity/ChatRoom.java
  src/main/java/com/yju/toonovel/domain/chatting/exception/ChatRoomAlreadyExistException.java
  src/main/java/com/yju/toonovel/domain/chatting/exception/ChatRoomAlreadyJoinException.java
  src/main/java/com/yju/toonovel/domain/chatting/exception/ChatRoomNotFoundException.java
  src/main/java/com/yju/toonovel/domain/chatting/exception/ChatRoomNotJoinException.java
  src/main/java/com/yju/toonovel/domain/chatting/exception/ChatRoomNotMatchUserException.java
  src/main/java/com/yju/toonovel/domain/chatting/exception/NotAuthorException.java
  src/main/java/com/yju/toonovel/domain/chatting/interceptor/StompHandler.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRoomRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java
  src/main/java/com/yju/toonovel/domain/chatting/service/ChatService.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/config/WebSocketConfig.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :sparkles: Feature

#91 [FEAT] ADMIN 관련 기능 구현
  src/main/java/com/yju/toonovel/domain/admin/controller/AdminController.java
  src/main/java/com/yju/toonovel/domain/admin/dto/EnrollListPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/admin/dto/EnrollListResponseDto.java
  src/main/java/com/yju/toonovel/domain/admin/dto/EnrollUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/admin/entity/EnrollHistory.java
  src/main/java/com/yju/toonovel/domain/admin/exception/AdminAuthenticationFailException.java
  src/main/java/com/yju/toonovel/domain/admin/exception/EnrollNotFoundException.java
  src/main/java/com/yju/toonovel/domain/admin/exception/EnrollNotMatchUserException.java
  src/main/java/com/yju/toonovel/domain/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/admin/repository/AdminRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/admin/repository/EnrollRepository.java
  src/main/java/com/yju/toonovel/domain/admin/service/AdminService.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java
  src/main/java/com/yju/toonovel/domain/novel/exception/AuthorNotFoundException.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelRepository.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/dto/AuthorRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/user/entity/Role.java
  src/main/java/com/yju/toonovel/domain/user/entity/User.java
  src/main/java/com/yju/toonovel/domain/user/exception/AlreadyAuthorException.java
  src/main/java/com/yju/toonovel/domain/user/repository/UserRepository.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :sparkles: Feature

#93 [FEAT] CloudWatch 연결
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: 🛠️ Setting, :sparkles: Feature

#96 [FEAT] 통계 기능 구현
  src/main/java/com/yju/toonovel/domain/admin/controller/AdminController.java
  src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java
  src/main/java/com/yju/toonovel/domain/novel/exception/NovelNotMatchAuthorException.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java
  src/main/java/com/yju/toonovel/domain/statistics/controller/StatisticsController.java
  src/main/java/com/yju/toonovel/domain/statistics/dto/AdminStatisticsResponseDto.java
  src/main/java/com/yju/toonovel/domain/statistics/dto/StatisticsResultResponseDto.java
  src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticsRepository.java
  src/main/java/com/yju/toonovel/domain/statistics/service/StatisticsService.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :sparkles: Feature

#98 [REFACTOR] 리프레쉬 토큰 로직 수정
  src/main/java/com/yju/toonovel/global/security/jwt/controller/TokenController.java
  src/main/java/com/yju/toonovel/global/security/jwt/service/TokenService.java
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/yju/toonovel/global/util/CookieUtils.java
Labels: :sparkles: Feature, :recycle: refactor

#100 [BUG] 내 작품 조회 버그
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
Labels: :bug: Bug

#103 [FEAT] 간단한 기능 추가 (정보 수정, 조회 기준 추가 등)
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostAllResponseDto.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostResponseDto.java
  src/main/java/com/yju/toonovel/domain/post/entity/Post.java
  src/main/java/com/yju/toonovel/domain/post/service/PostService.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserMyProfileResponseDto.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserProfileUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/user/entity/User.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
  src/main/java/com/yju/toonovel/global/common/Sort.java
Labels: :sparkles: Feature, :recycle: refactor

#106 [BUG] 실행 환경에 따라 메신저가 작동하지 않는 문제
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java
  src/main/java/com/yju/toonovel/domain/chatting/dto/ReplyDto.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRoomRepository.java
Labels: :bug: Bug

#110 [FEAT] API 기능 보충 (최신작가, 인기리뷰, 인기채팅룸)
  src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/dto/AuthorListPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/user/dto/AuthorListResponseDto.java
  src/main/java/com/yju/toonovel/domain/user/repository/ChatRoomCustomRepository.java
  src/main/java/com/yju/toonovel/domain/user/repository/ChatRoomCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepository.java
  src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :sparkles: Feature

#112 [FEAT] 작가 ID로 채팅방 가입하는 기능
  src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java
  src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java
Labels: :sparkles: Feature

#113 [REFACTOR] 유저 프로필 수정 API 수정
  src/main/java/com/yju/toonovel/domain/admin/service/AdminService.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserProfileUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/user/entity/User.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
  src/main/java/com/yju/toonovel/global/aws/controller/AwsController.java
  src/main/java/com/yju/toonovel/global/aws/service/S3Service.java
Labels: :bug: Bug, :recycle: refactor

#115 [REFACTOR] 리뷰 조회 API 수정
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewByUserResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
Labels: :recycle: refactor

#118 [BUG] 배포 환경에서 쿠키가 전달되지 않는 문제, Post 전체 조회 관련 문제
  src/main/java/com/yju/toonovel/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/yju/toonovel/global/util/CookieUtils.java
Labels: :bug: Bug

#120 [FEAT] Reply 조회 기능 추가
  src/main/java/com/yju/toonovel/domain/chatting/controller/ChatRoomHttpController.java
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java
  src/main/java/com/yju/toonovel/domain/chatting/dto/ReplyDto.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyCustomRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java
  src/main/java/com/yju/toonovel/domain/chatting/service/ChatService.java
Labels: :sparkles: Feature, :recycle: refactor

#122 [BUG] 배포 스크립트 수정
  scripts/gh_deploy.sh
Labels: :bug: Bug, :construction_worker: CI/CD

#124 [BUG] 채팅방 삭제 버그, ChatDto 리턴값 추가
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatDto.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyRepository.java
  src/main/java/com/yju/toonovel/domain/chatting/service/ChatRoomService.java
Labels: :bug: Bug, :sparkles: Feature

#127 [BUG] 작가 신청 버그 발생
  src/main/java/com/yju/toonovel/domain/admin/repository/EnrollRepository.java
  src/main/java/com/yju/toonovel/domain/user/exception/AlreadyAuthorEnrollException.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :bug: Bug

#130 [BUG] [REFACTOR] 작가 검색 시 무한 스크롤 문제, 채팅방 처음 조회 시 API 변경
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ReplyCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/user/dto/AuthorListResponseDto.java
  src/main/java/com/yju/toonovel/domain/user/repository/EnrollCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :bug: Bug, :recycle: refactor

#131 [BUG] 작가 통계 조회 버그 발생
  src/main/java/com/yju/toonovel/domain/admin/dto/EnrollListResponseDto.java
  src/main/java/com/yju/toonovel/domain/admin/entity/EnrollHistory.java
  src/main/java/com/yju/toonovel/domain/admin/repository/AdminRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/statistics/repository/StatisticsRepository.java
  src/main/java/com/yju/toonovel/domain/statistics/service/StatisticsService.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :bug: Bug

#137 [BUG] 좋아요 한 작품 조회시 필요한 데이터 넘어오지 않는 버그
  src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java
Labels: :bug: Bug, :recycle: refactor

#139 [FEAT] 채팅방 조회 Dto 수정
  src/main/java/com/yju/toonovel/domain/chatting/dto/ChatRoomResponseDto.java
  src/main/java/com/yju/toonovel/domain/chatting/repository/ChatRoomRepository.java
Labels: :sparkles: Feature
