Repository TooNovel/TooNovel-BE, pull requests merged in 2023-05, with the labels that each got.

#22 [FEAT] Novel 도메인 기능 구현
  build.gradle
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java
  src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelRequestDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/PlatformResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/UserLikeCheckResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Genre.java
  src/main/java/com/yju/toonovel/domain/novel/entity/LikeNovel.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java
  src/main/java/com/yju/toonovel/domain/novel/entity/NovelPlatform.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Platform.java
  src/main/java/com/yju/toonovel/domain/novel/exception/NovelNotFoundException.java
  src/main/java/com/yju/toonovel/domain/novel/exception/PlatformNotFoundException.java
  src/main/java/com/yju/toonovel/domain/novel/repository/LikeNovelCustomRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/LikeNovelCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/novel/repository/LikeNovelRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelPlatformRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/PlatformRepository.java
  src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
  src/main/java/com/yju/toonovel/domain/work/controller/WorkController.java
  src/main/java/com/yju/toonovel/domain/work/dto/WorkResponseDto.java
  src/main/java/com/yju/toonovel/domain/work/entity/Work.java
  src/main/java/com/yju/toonovel/domain/work/repository/WorkRepository.java
  src/main/java/com/yju/toonovel/domain/work/service/WorkService.java
  src/main/java/com/yju/toonovel/global/config/QueryDslConfig.java
  src/main/java/com/yju/toonovel/global/error/GlobalExceptionHandler.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
  src/main/resources/application.yaml
Labels: :sparkles: Feature

#24 [FEAT] Business Exception 처리 구현
  src/main/java/com/yju/toonovel/domain/novel/exception/NovelNotFoundException.java
  src/main/java/com/yju/toonovel/domain/novel/exception/PlatformNotFoundException.java
  src/main/java/com/yju/toonovel/domain/user/exception/InvalidUserException.java
  src/main/java/com/yju/toonovel/domain/user/exception/UserNotFoundException.java
  src/main/java/com/yju/toonovel/global/error/ErrorResponse.java
  src/main/java/com/yju/toonovel/global/error/GlobalExceptionHandler.java
  src/main/java/com/yju/toonovel/global/error/exception/BusinessException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/ExpiredRefreshTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/ExpiredTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/InvalidTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/filter/JwtAuthenticationEntryPoint.java
Labels: :sparkles: Feature

#26 [FEAT] Review 기능 구현
  src/main/java/com/yju/toonovel/domain/novel/exception/GenreNotFoundException.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelRepository.java
  src/main/java/com/yju/toonovel/domain/post/entity/Post.java
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/dto/AllReviewInWorkResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewAllByUserDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewLikeRegisterDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/review/entity/LikeReview.java
  src/main/java/com/yju/toonovel/domain/review/entity/Review.java
  src/main/java/com/yju/toonovel/domain/review/exception/DuplicateReviewException.java
  src/main/java/com/yju/toonovel/domain/review/exception/ReviewAlreadyLikedException.java
  src/main/java/com/yju/toonovel/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/yju/toonovel/domain/review/exception/ReviewNotMatchUserException.java
  src/main/java/com/yju/toonovel/domain/review/repository/LikeReviewRepository.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepository.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/service/LikeReviewService.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :sparkles: Feature

#27 [FEAT] 소설 검색 기능 구현 및 조회 기능 수정
  src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Genre.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/novel/service/NovelService.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :sparkles: Feature, :recycle: refactor

#29 [BUG] 검색 조회 Dto 수정
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java
Labels: :bug: Bug

#31 :bug: Review 도메인 수정
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
Labels: :bug: Bug, :recycle: refactor

#32 [FEAT] 추천 시스템 서버와 연결
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepository.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/recommend/controller/RecommendController.java
  src/main/java/com/yju/toonovel/domain/recommend/service/RecommendService.java
  src/main/java/com/yju/toonovel/global/config/WebConfig.java
  src/main/resources/application.yaml
Labels: :sparkles: Feature

#38 [REFACTOR] '좋아요' 한 작품 리스트 반환 수정
  src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :recycle: refactor

#43 [FEAT] API 명세서 작성을 위한 수정
  src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java
  src/main/java/com/yju/toonovel/domain/recommend/controller/RecommendController.java
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/global/common/Sort.java
Labels: :sparkles: Feature

#44 [REFACTOR] Review 도메인 리팩토링
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
Labels: :recycle: refactor

#46 [FEAT] Novel 도메인 기능 추가
  src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/entity/Novel.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelCustomRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/entity/Review.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/global/common/Sort.java
Labels: :sparkles: Feature, :recycle: refactor

#48 [SETTING] Readme 초안 작성
  README.md
Labels: :memo: Docs

#50 :bug: Review Paging 기능 수정
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewPaginationRequestDto.java
Labels: :bug: Bug

#51 [FEAT] Comment 도메인 기능 구현
  src/main/java/com/yju/toonovel/domain/comment/controller/CommentController.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentAllResponseDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/entity/Comment.java
  src/main/java/com/yju/toonovel/domain/comment/entity/LikeComment.java
  src/main/java/com/yju/toonovel/domain/comment/exception/CommentAlreadyLikedException.java
  src/main/java/com/yju/toonovel/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/yju/toonovel/domain/comment/exception/CommentNotMatchUserException.java
  src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepository.java
  src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/comment/repository/LikeCommentRepository.java
  src/main/java/com/yju/toonovel/domain/comment/service/CommentService.java
  src/main/java/com/yju/toonovel/domain/comment/service/LikeCommentService.java
  src/main/java/com/yju/toonovel/domain/post/exception/PostNotFoundException.java
  src/main/java/com/yju/toonovel/domain/post/repository/PostRepository.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :sparkles: Feature, :recycle: refactor

#54 [BUG] Review 조회 시 발생하는 버그
  src/main/java/com/yju/toonovel/domain/review/dto/AllReviewInWorkResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepository.java
Labels: :bug: Bug

#57 [FEAT] User 도메인 validation 추가
  build.gradle
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/user/entity/User.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :sparkles: Feature, :recycle: refactor

#59 [BUG] Comment, Reivew 버그 발생
  src/main/java/com/yju/toonovel/domain/comment/entity/Comment.java
  src/main/java/com/yju/toonovel/domain/comment/entity/LikeComment.java
  src/main/java/com/yju/toonovel/domain/review/entity/LikeReview.java
  src/main/java/com/yju/toonovel/domain/review/service/LikeReviewService.java
Labels: :bug: Bug

#62 [BUG] Review 조회 버그 및 리팩토링
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/dto/AllReviewInWorkResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewByNovelResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepository.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
Labels: :bug: Bug, :recycle: refactor

#65 [REFACTOR] Token 역할 분리
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
  src/main/java/com/yju/toonovel/global/security/jwt/JwtAuthentication.java
  src/main/java/com/yju/toonovel/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/yju/toonovel/global/security/jwt/controller/TokenController.java
  src/main/java/com/yju/toonovel/global/security/jwt/dto/TokenReIssueResponseDto.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/InvalidTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/RefreshTokenNotFoundException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/TokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/TokenExpiredException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/TokenInvalidException.java
  src/main/java/com/yju/toonovel/global/security/jwt/filter/ExceptionHandlerFilter.java
  src/main/java/com/yju/toonovel/global/security/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/yju/toonovel/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/yju/toonovel/global/security/jwt/service/TokenService.java
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/yju/toonovel/global/util/CookieUtils.java
Labels: :sparkles: Feature, :recycle: refactor

#68 [BUG] review 조회 버그 발생
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewByNovelResponseDto.java
Labels: :bug: Bug

#70 [SETTING] AWS 배포 준비
  .github/workflows/checkstyle.yml
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🛠️ Setting, :construction_worker: CI/CD

#72 [BUG] Review 조회 버그
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/global/config/WebConfig.java
Labels: :bug: Bug

#74 [FEAT] Swagger 문서화, 전역 Validation 적용
  build.gradle
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/entity/Comment.java
  src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelRequestDto.java
  src/main/java/com/yju/toonovel/domain/novel/entity/NovelPlatform.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/post/entity/Post.java
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewByUserResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewLikeRegisterDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/review/entity/Review.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
Labels: :sparkles: Feature, :recycle: refactor

#76 [REFACTOR] review, comment 도메인 일부 리팩토링
  src/main/java/com/yju/toonovel/domain/comment/controller/CommentController.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepository.java
  src/main/java/com/yju/toonovel/domain/comment/service/CommentService.java
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/review/exception/DuplicateReviewException.java
  src/main/java/com/yju/toonovel/domain/review/repository/ReviewRepository.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
Labels: :recycle: refactor

#77 [FEAT] Swagger 문서화, 전역 Validation 적용 - 2
  build.gradle
  src/main/java/com/yju/toonovel/domain/comment/controller/CommentController.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentAllResponseDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/dto/CommentUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/comment/repository/CommentRepository.java
  src/main/java/com/yju/toonovel/domain/novel/controller/NovelController.java
  src/main/java/com/yju/toonovel/domain/novel/dto/LikeNovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelDetailResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/NovelPaginationResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/PlatformResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/dto/UserLikeCheckResponseDto.java
  src/main/java/com/yju/toonovel/domain/novel/repository/NovelRepository.java
  src/main/java/com/yju/toonovel/domain/post/controller/PostController.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostAllResponseDto.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/yju/toonovel/domain/post/service/PostService.java
  src/main/java/com/yju/toonovel/domain/recommend/controller/RecommendController.java
  src/main/java/com/yju/toonovel/domain/review/controller/ReviewController.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewByNovelResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewByUserResponseDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewPaginationRequestDto.java
  src/main/java/com/yju/toonovel/domain/review/dto/ReviewRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/review/service/ReviewService.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserProfileResponseDto.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserRegisterRequestDto.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/config/SwaggerConfig.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
  src/main/java/com/yju/toonovel/global/security/oauth/dto/OAuthAttributes.java
  src/main/resources/application.yaml
Labels: :bug: Bug, :sparkles: Feature, :recycle: refactor

#81 [SETTING] logback 추가 및 모니터링 도입
  .github/workflows/checkstyle.yml
  .github/workflows/deploy.yml
  build.gradle
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: 🛠️ Setting, :sparkles: Feature

#83 [SETTING] 운영 환경과 개발 환경 설정 분리
  .github/workflows/deploy.yml
  README.md
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
Labels: 🛠️ Setting, :memo: Docs, :recycle: refactor

#84 [FEAT] S3 이미지 업로드 기능 구현
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/yju/toonovel/domain/comment/controller/CommentController.java
  src/main/java/com/yju/toonovel/global/aws/controller/AwsController.java
  src/main/java/com/yju/toonovel/global/aws/service/S3Service.java
  src/main/java/com/yju/toonovel/global/config/AwsConfig.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/resources/application.yaml
Labels: :sparkles: Feature
