Repository TooNovel/TooNovel-BE, pull requests merged in 2023-04, with the labels that each got.

#7 [SETTING] 프로젝트 초기 설정
  build.gradle
  src/main/java/com/yju/toonovel/ToonovelApplication.java
  src/main/java/com/yju/toonovel/domain/user/entity/Provider.java
  src/main/java/com/yju/toonovel/domain/user/entity/Role.java
  src/main/java/com/yju/toonovel/domain/user/entity/User.java
  src/main/java/com/yju/toonovel/global/common/entity/BaseEntity.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/config/WebConfig.java
  src/main/java/com/yju/toonovel/global/error/ErrorResponse.java
  src/main/java/com/yju/toonovel/global/error/GlobalExceptionHandler.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
  src/main/resources/application.properties
Labels: 🛠️ Setting, :sparkles: Feature

#12 :bug: @ColumnDefault("0")이 적용되지 않는 문제 해결
  src/main/java/com/yju/toonovel/domain/post/entity/Post.java
Labels: :bug: Bug

#15 [REFACTOR] 토큰 전달 방식 변경 및 회원 가입 기능 추가
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: :sparkles: Feature, :recycle: refactor

#16 [FEAT] JWT 기반 인증 및 OAuth 소셜 로그인 구현
  build.gradle
  src/main/java/com/yju/toonovel/domain/post/controller/PostController.java
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserProfileResponseDto.java
  src/main/java/com/yju/toonovel/domain/user/dto/UserRegisterRequestDto.java
  src/main/java/com/yju/toonovel/domain/user/entity/User.java
  src/main/java/com/yju/toonovel/domain/user/exception/InvalidUserException.java
  src/main/java/com/yju/toonovel/domain/user/exception/UserNotFoundException.java
  src/main/java/com/yju/toonovel/domain/user/repository/UserRepository.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
  src/main/java/com/yju/toonovel/domain/work/controller/WorkController.java
  src/main/java/com/yju/toonovel/global/config/SecurityConfig.java
  src/main/java/com/yju/toonovel/global/config/WebConfig.java
  src/main/java/com/yju/toonovel/global/error/exception/ErrorCode.java
  src/main/java/com/yju/toonovel/global/security/jwt/JwtAuthentication.java
  src/main/java/com/yju/toonovel/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/yju/toonovel/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/yju/toonovel/global/security/jwt/dto/RefreshTokenCreateRequestDto.java
  src/main/java/com/yju/toonovel/global/security/jwt/entity/RefreshToken.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/ExpiredRefreshTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/ExpiredTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/exception/InvalidTokenException.java
  src/main/java/com/yju/toonovel/global/security/jwt/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/yju/toonovel/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/yju/toonovel/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/yju/toonovel/global/security/oauth/CustomOAuth2User.java
  src/main/java/com/yju/toonovel/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/yju/toonovel/global/security/oauth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/yju/toonovel/global/security/oauth/dto/GoogleOAuth2UserInfo.java
  src/main/java/com/yju/toonovel/global/security/oauth/dto/KakaoOAuth2UserInfo.java
  src/main/java/com/yju/toonovel/global/security/oauth/dto/OAuth2UserInfo.java
  src/main/java/com/yju/toonovel/global/security/oauth/dto/OAuthAttributes.java
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/yju/toonovel/global/security/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/yju/toonovel/global/util/CookieUtils.java
  src/main/resources/application.yaml
Labels: :sparkles: Feature

#18 [FEAT] User 탈퇴 기능 구현
  src/main/java/com/yju/toonovel/domain/user/controller/UserController.java
  src/main/java/com/yju/toonovel/domain/user/service/UserService.java
Labels: :sparkles: Feature
